/*
 * This source file was generated by the Gradle 'init' task
 */
package com.toy.tcpip

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun sampleTest() {
        assertTrue(true)
    }
}
